version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: bsc_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: bsc_user
      POSTGRES_PASSWORD: bsc_password
      POSTGRES_DB: bsc_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: